################################################################################################################################################
# Template de Github Actions - Stack Completa de AppSec
# Elaboração:
# Emerson Xavier - emerson.xavier@keeggo.com
# Michel Santana - michel.santana@keeggo.com
#
# Stack de Ferramentas de App Sec:
# - Checkout do Código
# - Build da Aplicação Java
# - OpenText Debricked - Análise de Componentes de Terceiros
# - OpenText Fortify Static Code Analyzer - Análise Estática
# - Mobb Fixer - Correção Automatizada de Código
#
#
################################################################################################################################################

trigger:
- none
stages:
- stage: Build
  jobs:
    - job: Build
      displayName: Building IWA Project
 
      pool: Default
      steps:
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'LocalDirectory'
          jdkFile: 'D:\Tools\jdk-17.0.12.7-hotspot.zip'
          jdkDestinationDirectory: 'D:\Tools\jdk-17.0.12.7-hotspot\'
      # Use Node.js ecosystem v0
      # Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH.
      - task: NodeTool@0
        inputs:
          versionSource: 'spec' # 'spec' | 'fromFile'. Required. Source of version. Default: spec.
          #versionSpec: '6.x' # string. Optional. Use when versionSource = spec. Version Spec. Default: 6.x.
          #versionFilePath: # string. Optional. Use when versionSource = fromFile. Path to the .nvmrc file. 
          #checkLatest: false # boolean. Check for Latest Version. Default: false.
          #force32bit: false # boolean. Use 32 bit version on x64 agents. Default: false.
        # Advanced
          nodejsMirror: 'https://nodejs.org/dist' # string. Set source for Node.js binaries. Default: https://nodejs.org/dist.
          #retryCountOnDownloadFails: '5' # string. Set retry count when nodes downloads failed. Default: 5.
          #delayBetweenRetries: '1000' # string. Set delay between retries. Default: 1000.
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

    - job: SAST
      displayName: Fortify SAST
      dependsOn:
       - Build
      pool: Default
      steps:
      - task: FortifyScanCentralSAST@7
        inputs:
          scanCentralCtrlUrl: '$(_FCLI_DEFAULT_SCC_URL)'
          scanCentralClientToken: '$(_FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN)'
          sscUrl: '$(_FCLI_DEFAULT_SSC_URL)'
          sscCiToken: '$(_FCLI_DEFAULT_SSC_CI_TOKEN)'
          uploadToSSC: true
          applicationName: 'IWA'
          applicationVersion: 'java'
          buildTool: 'none'
          block: true
          outputFile: 'APP.fpr'