################################################################################################################################################
# Template de Github Actions - Stack Completa de AppSec
# Elaboração:
# Emerson Xavier - emerson.xavier@keeggo.com
# Michel Santana - michel.santana@keeggo.com
#
# Stack de Ferramentas de App Sec:
# - Checkout do Código
# - Build da Aplicação Java
# - SonarQube - Análise de Qualidade do Código
# - OWASP Dependency Track - Análise de Componentes de Terceiros
# - OpenText Debricked - Análise de Componentes de Terceiros
# - OpenText Fortify Static Code Analyzer - Análise Estática
# - Mobb Fixer - Correção Automatizada de Código
#
#
################################################################################################################################################

trigger:
- none
stages:
- stage: Build
  jobs:
    - job: Build
      displayName: Building IWA Project
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

    - job: SAST
      displayName: Fortify SAST
      dependsOn:
       - Build
      pool:
       vmImage: 'ubuntu-latest'
      container:
        image: fortifydocker/fortify-ci-tools:5.4.1-jdk-17
        options: "--add-host=https://fortify-demo-lab.keeggo.com/"
        env:
          FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN: $(_FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN)
          FCLI_DEFAULT_SSC_USER: $(_FCLI_DEFAULT_SSC_USER)
          FCLI_DEFAULT_SSC_PASSWORD: $(_FCLI_DEFAULT_SSC_PASSWORD)
          FCLI_DEFAULT_SSC_CI_TOKEN: $(_FCLI_DEFAULT_SSC_CI_TOKEN)
          FCLI_DEFAULT_SSC_URL: $(_FCLI_DEFAULT_SSC_URL)
          SSC_APP_VERSION_ID: $(_SSC_APP_VERSION_ID)
          SC_SAST_SENSOR_VERSION: 24.2
      steps:
      - script: |
      
          java -version
          fcli -V
          debricked -v
          # Loga no Fortify SSC e SC-SAST Controller
          fcli ssc session login --url=${{ secrets.SSC_URL }} --ci-token=${{ secrets.SSC_TOKEN }}
          fcli sc-sast session login --client-auth-token=${{ secrets.CLIENT_AUTH_TOKEN }} --ssc-url=${{ secrets.SSC_URL }} --ssc-ci-token=${{ secrets.SSC_TOKEN }}
          # Empacota a Aplicação para o Scancentral
          scancentral package --build-tool none -o APP.zip
          # Envia o Artefato para o Scancentral Controller
          fcli sc-sast scan start --package-file=APP.zip --sensor-version=24.2 --publish-to ${{ env.App-Version  }} --ssc-ci-token=${{ secrets.SSC_TOKEN }} --store job:jobToken
          # Debricked Scan
          debricked scan -t ${{ secrets.DEBRICKED_TOKEN }} -r=${{ env.App-Version  }} --commit=${{ env.GITHUB_RUN_ID }}
          # Importa os Resultados Debricked no SSC  
          fcli ssc artifact import-debricked -t ${{ secrets.DEBRICKED_TOKEN }} --av=${{ env.App-Version  }} -r=${{ env.App-Version  }} --branch=$GITHUB_REF_NAME
          # Espera Scan Fortify Acabar  
          fcli sc-sast scan wait-for --any-ssc-state PROCESS_COMPLETE --timeout 2h ::job::jobToken --store sscArtifactId
          # Consulta ID do Ultimo Artefacto
          fcli ssc artifact list --appversion ${{ env.App-Version  }} --query "['scanTypes'].contains('SCA')" --output 'expr={id}\n' > out.txt
          # Recuperação do Ultimo Artefacto Scaneado
          # run: fcli ssc artifact download "$(head -1 out.txt)" -f='app.fpr'

          echo Setting connection with Fortify Platform
          echo $FORTIFY_SSC_IP fortify.cyberxdemo.com >> /etc/hosts
          #Use --insecure switch if the SSL certificate is self generated.
          fcli ssc session login
          fcli sc-sast session login
          
          scancentral package -bt mvn -o package.zip
          fcli sc-sast scan start --publish-to=$SSC_APP_VERSION_ID --sensor-version=$SC_SAST_SENSOR_VERSION --package-file=package.zip --store=Id

          fcli sc-sast scan wait-for ::Id:: --interval=30s
          fcli ssc issue count --appversion=$SSC_APP_VERSION_ID

          echo Terminating connection with Fortify Platform
          fcli sc-sast session logout
          fcli ssc session logout
            
        displayName: Scan Central Scan
        continueOnError: false