
################################################################################################################################################
# Template de Github Actions - Stack Completa de AppSec
# Elaboração:
# Emerson Xavier - emerson.xavier@keeggo.com
# Michel Santana - michel.santana@keeggo.com
#
# Stack de Ferramentas de App Sec:
# - Checkout do Código
# - Build da Aplicação Java
# - SonarQube - Análise de Qualidade do Código
# - OWASP Dependency Track - Análise de Componentes de Terceiros
# - Semgrep OSS - SAST Scan
# - Mobb Fixer - Correção Automatizada de Código
#
#
################################################################################################################################################

name: AppSec - Pipeline

# Gatilho de Disparo
on:
  workflow_dispatch:

# Jobs
jobs:
 Build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
          App-Version: 'IWA:java'
    steps:
    # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4
 
      # Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      
       #Sonarqube
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      # Mvn    
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      # Build   
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=IWA-Java -Dsonar.projectName='IWA-Java'
      - name: Armazena em Cache o Build
        id: cache-build
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}
 SCA:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
          App-Version: 'IWA:java'
    steps:
      - uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}
      #CDXGen para Gerar SBOM e Submeter ao DT
      - uses: AppThreat/cdxgen-action@v1
        with:
          output: "./reports/bom.xml"
          serverUrl: "https://fortify-demo-lab-utils.keeggo.com"
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          projectName: "IWA"
          projectVersion: "java"
      - name: Armazena em Cache o Build
        id: cache-build
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}
          
 Semgrep_AppSec_Stack:
      # User definable name of this GitHub Actions job.
    name: semgrep-oss/scan
    # If you are self-hosting, change the following `runs-on` value: 
    runs-on: ubuntu-latest
    needs: [SCA]
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

      # Run the "semgrep scan" command on the command line of the docker image.
    steps:
    # Restaura Cache de Build
    - uses: actions/cache/restore@v3
      id: restore-build
      with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}
    # Executa Semgrep Scan
    - run: semgrep scan --sarif --sarif-output=iwa-java.sarif
    # Importa Resultados no GH Security
    - name: Importar Semgrep Results Sarif on GH
      uses: github/codeql-action/upload-sarif@v3
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: iwa-java.sarif 
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: Semgrep
